FROM alpine:latest

WORKDIR /app

# Installare GCC e Make

RUN apk update && \
	apk add --no-cache gcc make libc-dev linux-headers netcat-openbsd

COPY . /app/

# Compilare ed eseguire il client
RUN make run_client

# Esporre la porta 10000
EXPOSE 10000

CMD ["./client", "server", "10000", "1"]
