@startuml
start
:Inizializza Supervisione Supermercato;
:Dormi per 10 Secondi;

repeat
  :Blocca Mutex Supermercato;
  if (Possiamo Ammettere Nuovi Clienti?) then (sì)
    :Ammetti Nuovi Clienti;
    :Aggiorna Conto Clienti;
    :Stampa Stato Ammissione;
  else (no)
    :Stampa Nessuno Spazio Disponibile;
    stop
  endif
  :Sblocca Mutex Supermercato;
  :Dormi per 10 Secondi;
repeat while (vero)

stop
@enduml
