FROM alpine:latest

WORKDIR /app

RUN apk update && \
	apk add --no-cache gcc make libc-dev linux-headers netcat-openbsd

COPY . /app/

RUN gcc -c -pthread server.c -o server.o
RUN gcc -c -pthread models_impl/supermercato.c -o supermercato.o
RUN gcc -c -pthread models_impl/cassa.c -o cassa.o
RUN gcc -c -pthread models_impl/cliente.c -o cliente.o
RUN gcc -pthread server.o supermercato.o cassa.o cliente.o -o server

EXPOSE 10000

CMD ["./server", "10000", "localhost", "5"]

